# Generated by Django 4.1.2 on 2025-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vantry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
