# Generated by Django 4.2.20 on 2025-04-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vantry", "0002_product_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="off_id",
            new_name="barcode",
        ),
    ]
