# Generated by Django 4.2.20 on 2025-04-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vantry", "0003_rename_off_id_product_barcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
