# Generated by Django 4.2.20 on 2025-04-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vantry", "0004_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="storage",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="vantry.storage",
            ),
            preserve_default=False,
        ),
    ]
